[connections.snowflake]
connection_name = "my_connection_snow"
account = "KJIZNYL-BIB20935"
user = "AXELVISEO"
authenticator = "externalbrowser"
role = "ACCOUNTADMIN"
warehouse = "COMPUTE_WH"
database = "SMOOTHIES"
schema = "PUBLIC"
